version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/sudden

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install node dependencies
          command: yarn

      - run:
          name: Build project
          command: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Persist the dist folder into the workspace for use in publish job.
      - persist_to_workspace:
          root: ~/sudden
          # files to persist (relative to the root of the project)
          paths:
            - dist
            - node_modules

  test:
    executor: node-executor
    steps:
      - checkout

      - attach_workspace:
          at: ~/sudden

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Publish code coverage
          command: yarn coverage

  publish:
    executor: node-executor
    filters:
      branches:
        only: master
      tags:
        only: /v[0-9]+(\.[0-9]+)*/
    steps:
      - checkout

      - attach_workspace:
          at: ~/sudden

      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build

      - test:
          requires:
            - build

      - publish:
          requires:
            - test
