version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:10.16.0
    working_directory: ~/sudden

jobs:
  deps:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/sudden
          paths:
            - node_modules

  build:
    executor: node-executor
    steps:
      - checkout

      - attach_workspace:
          at: ~/sudden

      - run:
          name: Build project
          command: yarn build

      - persist_to_workspace:
          root: ~/sudden
          paths:
            - dist

  test:
    executor: node-executor
    steps:
      - checkout

      - attach_workspace:
          at: ~/sudden

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Publish code coverage
          command: yarn coverage

  publish:
    executor: node-executor
    steps:
      - checkout

      - attach_workspace:
          at: ~/sudden

      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish

workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - deps

      - build:
          requires:
            - deps

      - test:
          requires:
            - deps

      - publish:
          requires:
            - build
            - test

          filters:
            branches:
              ignore: /.*/
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
